[tool.poetry]
name = "article-management"
version = "0.1.0"
description = ""
authors = ["PanBard"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
natsort = "^8.4.0"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
